package calc.equil;

import org.junit.jupiter.api.Tag;
import org.junit.jupiter.api.Test;

import system.database.TdbParser;
import system.database.UnaryGibbsBuilder;
import system.model.GibbsEnergyModel;
import system.model.PhaseModelFactory;
import system.model.cvm.CecTerm;
import system.model.cvm.CvmGibbsModel;
import system.model.cvm.CvmPhaseData;
import system.model.cvm.CvmPhaseSpec;
import system.model.unary.ElementGibbs;
import system.ports.EquilibriumResult;

import java.util.List;
import java.util.Locale;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertNotNull;
import static org.junit.jupiter.api.Assertions.assertTrue;

/**
 * Step 7: cross-checks {@link EquilibriumSolverV2}'s internal CVM
 * {@code u}-relaxation against an independent reference from CEWorkbench's
 * {@code HillertSolver}/{@code CVMGibbsModel} (a separate codebase --
 * {@code C:\Users\admin\codes\CEWorkbench}, read-only reference, not a
 * dependency of this project).
 *
 * <p><strong>Classified as EXTERNAL (CEWorkbench reference validation).</strong>
 *
 * <h2>What is being validated</h2>
 * {@link EquilibriumSolverV2} is the ONE shared equilibrium solver in this
 * project -- there is no separate {@code CvmNewtonSolver}/
 * {@code CvmPhaseMinimizer} here, by design (see class notes on
 * {@link system.model.cvm.CvmGibbsModel#getInitialInternalVars}). This test
 * proves that, for a single fixed-composition CVM phase, the SAME global
 * Newton iteration this solver uses for every model (CEF or CVM) actually
 * drives the CVM internal correlation functions {@code u} to the same
 * stationary point ({@code dG/du = 0}) that a fixed-composition inner
 * solver would find.
 *
 * <h2>Reference generation (not committed here)</h2>
 * The comparison numbers below were generated by running, in the CEWorkbench
 * checkout:
 * <pre>
 *   ./gradlew runScratch -PscratchClass=org.ce.scratch.VZrHillertCrossCheckRef
 * </pre>
 * which builds {@code CvmGeometry.build("V-Zr","BCC_A2","T")} with the same
 * Table 11 CECs used below, evaluates the fully-disordered random state
 * (composition/geometry only, no ECI dependence -- the variable-ordering
 * cross-check), and runs CEWorkbench's {@code CvmNewtonSolver} (their
 * fixed-composition inner solver; used ONLY as a reference-number generator
 * here, never ported or reproduced in this codebase) to obtain the
 * converged {@code u}, {@code G}, and the {@code HillertSolver.PhaseStep}
 * u-block stationarity quantities ({@code gmu}, {@code gmuu}) at that point.
 * That scratch file is NOT committed (CEWorkbench is a separate repository);
 * its output is reproduced in this class's javadoc and in the assertions'
 * tolerances below.
 *
 * <h2>Variable-ordering mapping (confirmed identity)</h2>
 * expcvm10's {@code u2ListNames = [v4AB, v3AB, v22AB, v21AB, xA, xB]}
 * ({@link system.model.cvm.CvmPhaseData}) is byte-for-byte the same name
 * list, in the same order, as CEWorkbench's {@code CvmGeometry.basis.cfNames}
 * for the same {@code (V-Zr, BCC_A2, T)} system. The random (fully
 * disordered) state at x=[0.95,0.05] confirms this numerically -- CEWorkbench
 * reports {@code uFull = [0.0022562500, -0.0427500000, 0.0475000000,
 * 0.0475000000, 0.95, 0.05]}, which matches
 * {@code CvmGibbsModel.getInitialInternalVars(x)} below to full double
 * precision (see {@link #randomStateMatchesCEWorkbenchOrdering()}). No
 * permutation or sign flip is needed: identity mapping, index-for-index.
 *
 * <h2>Reference numbers (CEWorkbench HillertSolver-compatible, T=1000K)</h2>
 * <pre>
 * x=[0.95,0.05]:
 *   u_Hillert = [0.002196933159357, -0.043005411713481,
 *                0.047584831411195, 0.047598671398244]
 *   G_Hillert (absolute, g0m+gm) = -46395.41632316916 J/mol
 *   max|gmu|_Hillert = 9.444898e-08
 *   gmuu pivots (Cholesky) all positive -> locally minimum-like
 *
 * x=[0.6,0.4]:
 *   u_Hillert = [0.058687110860256, -0.049349296848699,
 *                0.241942572957741, 0.242188965219370]
 *   G_Hillert (absolute) = -53786.60905607974 J/mol
 *   max|gmu|_Hillert = 1.739409e-10
 *   gmuu pivots all positive
 *
 * x=[0.5,0.5]:
 *   u_Hillert = [0.063776625493807, -0.000071205258847,
 *                0.252049957981641, 0.252286592216877]
 *   G_Hillert (absolute) = -54836.12953069658 J/mol
 *   max|gmu|_Hillert = 5.968559e-10
 *   gmuu pivots all positive
 * </pre>
 *
 * <h2>Normalization confirmed to match</h2>
 * Both models express {@code G} per mole of formula unit (1 atom, disordered
 * single-site BCC_A2 -- {@code nfu()=1} on the expcvm10 side, and
 * CEWorkbench's {@code G = G0m + Gm} is per-formula-unit by the same
 * convention), use the identical Table 11 CEC values
 * ({@code E21VZr=-1120-0.159T}, {@code E22VZr=-746.7-0.106T}, {@code E3VZr=120},
 * {@code v4VZr} not reported -> 0) applied to the identical cluster
 * geometry, and both reference the SGTE unary Gibbs energies of pure V and
 * Zr in the BCC_A2 structure ({@code GHSERVV}/{@code GHSERZR}, here read from
 * {@code data/VZR-re2.TDB} via {@link UnaryGibbsBuilder}, matching
 * CEWorkbench's own SGTE unary evaluation). The absolute G values above are
 * therefore on the same footing as {@code CvmGibbsModel.G(T,P,y)}.
 */
@Tag("external")
class EquilibriumSolverV2CvmHillertCrossCheckTest {

    private static final String TDB = "data/VZR-re2.TDB";
    private static final double T = 1000.0;
    private static final double P = 101325.0;

    /** ncf for this binary BCC_A2 tetrahedron-approximation geometry. */
    private static final int NCF = 4;

    // ------------------------------------------------------------------
    // Reference numbers from CEWorkbench (see class javadoc for how these
    // were generated -- org.ce.scratch.VZrHillertCrossCheckRef).
    // ------------------------------------------------------------------

    private static final double[] U_HILLERT_95_05 = {
            0.002196933159356511, -0.04300541171348146,
            0.04758483141119484, 0.04759867139824415};
    private static final double G_HILLERT_95_05 = -46395.41632316916;

    private static final double[] U_HILLERT_60_40 = {
            0.05868711086025605, -0.04934929684869908,
            0.2419425729577407, 0.2421889652193703};
    private static final double G_HILLERT_60_40 = -53786.60905607974;

    private static final double[] U_HILLERT_50_50 = {
            0.06377662549380744, -7.120525884717515e-05,
            0.2520499579816408, 0.2522865922168774};
    private static final double G_HILLERT_50_50 = -54836.12953069658;

    /** Fully-disordered random state at x=[0.95,0.05] (geometry+composition
     *  only, no ECI dependence) -- the ordering cross-check reference. */
    private static final double[] U_RANDOM_HILLERT_95_05 = {
            0.002256249999999987, -0.04275000000000004,
            0.04750000000000004, 0.04750000000000004,
            0.9500000000000000, 0.05000000000000004};

    // ------------------------------------------------------------------
    // BCC_A2 (CVM) construction: verbatim copy of the Step 6 fixture
    // (EquilibriumSolverV2CefCvmTwoPhaseEndToEndTest#buildBccModel /
    // #buildBccPhaseData) -- same validated V-Zr Table 11 CECs, same
    // component-agnostic tetrahedron-approximation geometry.
    // ------------------------------------------------------------------

    private static CvmGibbsModel buildBccModel(TdbParser parser) {
        CvmPhaseData data = buildBccPhaseData();

        // Real V-Zr bcc CECs, Jindal & Lele, CALPHAD 89 (2025) 102825,
        // Table 11: E21VZr=-1120-0.159T (I-neighbor), E22VZr=-746.7-0.106T
        // (II-neighbor), E3VZr=120 (triangle); v4VZr not reported (0).
        List<CecTerm> cecTerms = List.of(
                new CecTerm("v4AB", 0.0, 0.0),
                new CecTerm("v3AB", 120.0, 0.0),
                new CecTerm("v22AB", -746.7, -0.106),
                new CecTerm("v21AB", -1120.0, -0.159));

        ElementGibbs ghserV = UnaryGibbsBuilder.build("V", parser.getUnderlyingTdb());
        ElementGibbs ghserZr = UnaryGibbsBuilder.build("ZR", parser.getUnderlyingTdb());

        CvmPhaseSpec spec = new CvmPhaseSpec(data, cecTerms,
                new ElementGibbs[]{ghserV, ghserZr}, List.of("V", "ZR"));

        return (CvmGibbsModel) PhaseModelFactory.buildCvm(spec);
    }

    /** Verbatim copy of the Step 3-6 binary BCC_A2 tetrahedron-approximation
     *  fixture -- see {@code EquilibriumSolverV2CefCvmTwoPhaseEndToEndTest}
     *  for the full provenance note. */
    private static CvmPhaseData buildBccPhaseData() {
        int nComp = 2;
        int ncf = 4;
        int tcdis = 5;

        double[] mhdis = {6.0, 12.0, 4.0, 3.0, 1.0};
        double[] kbdis = {1.0, -1.0, 1.0, 1.0, -1.0};

        int[] lc = {1, 1, 1, 1, 1};

        int[][] lcv = {
                {6}, // tetrahedron
                {6}, // triangle
                {3}, // pair 2NN
                {3}, // pair 1NN
                {2}, // point
        };

        double[][] mh = {
                {1.0}, {1.0}, {1.0}, {1.0}, {1.0}
        };

        double[][][] wcv = {
                {{1, 4, 4, 2, 4, 1}},
                {{1, 2, 1, 1, 2, 1}},
                {{1, 2, 1}},
                {{1, 2, 1}},
                {{1, 1}},
        };

        double[][][][] cmat = {
                // t=0 tetrahedron
                {{
                        {1.0, 1.0, 0.0, -2.0, 1.0, 0.0},
                        {-1.0, -0.5, -0.5, 1.0, 0.0, 0.0},
                        {1.0, 0.0, 1.0, -1.0, 0.0, 0.0},
                        {1.0, 0.0, 0.0, 0.0, 0.0, 0.0},
                        {-1.0, 0.5, -0.5, 1.0, 0.0, 0.0},
                        {1.0, -1.0, 0.0, -2.0, 0.0, 1.0},
                }},
                // t=1 triangle
                {{
                        {0.0, 0.5, -0.5, -1.0, 1.0, 0.0},
                        {0.0, -0.5, 0.5, 0.0, 0.0, 0.0},
                        {0.0, 0.5, -0.5, 1.0, 0.0, 0.0},
                        {0.0, -0.5, -0.5, 1.0, 0.0, 0.0},
                        {0.0, 0.5, 0.5, 0.0, 0.0, 0.0},
                        {0.0, -0.5, -0.5, -1.0, 0.0, 1.0},
                }},
                // t=2 pair 2NN
                {{
                        {0.0, 0.0, 0.0, -1.0, 1.0, 0.0},
                        {0.0, 0.0, 0.0, 1.0, 0.0, 0.0},
                        {0.0, 0.0, 0.0, -1.0, 0.0, 1.0},
                }},
                // t=3 pair 1NN
                {{
                        {0.0, 0.0, -1.0, 0.0, 1.0, 0.0},
                        {0.0, 0.0, 1.0, 0.0, 0.0, 0.0},
                        {0.0, 0.0, -1.0, 0.0, 0.0, 1.0},
                }},
                // t=4 point
                {{
                        {0.0, 0.0, 0.0, 0.0, 1.0, 0.0},
                        {0.0, 0.0, 0.0, 0.0, 0.0, 1.0},
                }},
        };

        int uListLen = 6;

        double[][] cfCoeffs = new double[uListLen][uListLen];
        for (int i = 0; i < uListLen; i++) cfCoeffs[i][i] = 1.0;

        String[] u2Names = {"v4AB", "v3AB", "v22AB", "v21AB", "xA", "xB"};
        String[] eNames = {"v4AB", "v3AB", "v22AB", "v21AB"};

        return new CvmPhaseData(
                "BCC_A2", nComp, ncf,
                tcdis, mhdis, kbdis,
                lc, lcv, mh, wcv, cmat,
                uListLen, cfCoeffs,
                u2Names, eNames);
    }

    // ------------------------------------------------------------------
    // Item 4/CRITICAL: variable-ordering mapping cross-check. The random
    // (fully disordered) state depends only on geometry + composition, not
    // on ECIs, so it is the cleanest possible ordering probe -- if this
    // does not match elementwise, no downstream u-comparison can be
    // trusted without a permutation/sign correction.
    // ------------------------------------------------------------------
    @Test
    void randomStateMatchesCEWorkbenchOrdering() throws Exception {
        TdbParser parser = new TdbParser();
        parser.load(TDB);
        CvmGibbsModel bcc = buildBccModel(parser);

        double[] x = {0.95, 0.05};
        double[] yRandom = bcc.getInitialInternalVars(x);

        System.out.println("=== Random-state ordering cross-check (x=[0.95,0.05]) ===");
        System.out.println("expcvm10  y = " + java.util.Arrays.toString(yRandom));
        System.out.println("Hillert   y = " + java.util.Arrays.toString(U_RANDOM_HILLERT_95_05));

        assertEquals(U_RANDOM_HILLERT_95_05.length, yRandom.length,
                "Random-state vector length must match (ncf+K).");
        for (int i = 0; i < yRandom.length; i++) {
            assertEquals(U_RANDOM_HILLERT_95_05[i], yRandom[i], 1.0e-9,
                    "Random-state entry [" + i + "] must match CEWorkbench "
                    + "(identity ordering, no permutation/sign flip needed).");
        }
    }

    // ------------------------------------------------------------------
    // Core cross-check: run x=[0.95,0.05] (primary), [0.6,0.4], [0.5,0.5]
    // (secondary) through EquilibriumSolverV2 with composition pinned to
    // the target (single-phase, fixed-x), and compare the converged CVM
    // internal state against the CEWorkbench HillertSolver-compatible
    // reference.
    // ------------------------------------------------------------------

    @Test
    void primaryComposition95_05MatchesHillertReference() throws Exception {
        runCrossCheck(new double[]{0.95, 0.05}, U_HILLERT_95_05, G_HILLERT_95_05, "x=[0.95,0.05]");
    }

    @Test
    void secondaryComposition60_40MatchesHillertReference() throws Exception {
        runCrossCheck(new double[]{0.6, 0.4}, U_HILLERT_60_40, G_HILLERT_60_40, "x=[0.6,0.4]");
    }

    @Test
    void secondaryComposition50_50MatchesHillertReference() throws Exception {
        runCrossCheck(new double[]{0.5, 0.5}, U_HILLERT_50_50, G_HILLERT_50_50, "x=[0.5,0.5]");
    }

    private void runCrossCheck(double[] target, double[] uHillert, double gHillert, String label)
            throws Exception {

        TdbParser parser = new TdbParser();
        parser.load(TDB);
        CvmGibbsModel bcc = buildBccModel(parser);

        List<GibbsEnergyModel> candidates = List.of(bcc);

        double[] y0 = bcc.getInitialInternalVars(target);
        assertTrue(bcc.isValid(y0), "CVM initial constitution must be valid: " + label);

        double gInitial = bcc.G(T, P, y0);

        EquilibriumSolverV2 solver = new EquilibriumSolverV2();
        // Real V-Zr GHSER/mu magnitudes (~1e4-1e5 J) push the solver's
        // ABSOLUTE (unscaled) stationarity residual -- ||G_Y - J_M^T*mu||,
        // computed as a difference of two O(1e5) quantities -- to a
        // floating-point-roundoff floor around 1e-6..1e-7, even once
        // DeltaY/DeltaMu have already reached machine precision (see the
        // verbose Sundman trace: DeltaY ~1e-16 by iteration 4, stationarity
        // stuck at ~1e-6 forever after). This is the same class of
        // conditioning-driven residual floor already documented for this
        // CVM Hessian (O(1e4)-O(1e10) diagonal spread), just showing up on
        // the x-block stationarity term instead of DeltaY -- a genuine
        // numerical floor of this problem's magnitude scale, not
        // non-convergence. Matches the tolerance already used for this
        // same real-CEC V-Zr system in
        // EquilibriumSolverV2CefCvmTwoPhaseEndToEndTest (1e-6), rather than
        // the tighter 1e-8 that only the small-magnitude fake-CEC fixture
        // (EquilibriumSolverV2CvmSinglePhaseEndToEndTest) can meet.
        solver.setTolerance(1.0e-6);
        solver.setVerbose(false);

        solver.setInitialStateForTest(
                new int[]{0},
                new double[][]{y0},
                new double[]{1.0});

        EquilibriumResult result = solver.solve(T, P, target, candidates);

        assertNotNull(result);
        assertTrue(result.isConverged(), label + ": single-CVM-phase solve should converge.");

        assertEquals(1, result.getStablePhases().size());
        EquilibriumResult.PhaseResult stable = result.getStablePhases().get(0);
        assertEquals("BCC_A2", stable.phaseName);
        assertEquals("CVM", stable.modelType);

        double[] yConverged = stable.y;
        assertNotNull(yConverged);
        assertTrue(bcc.isValid(yConverged), label + ": converged CVM state must remain valid.");

        // ---- independent direct-model evaluation (not through the solver) ----
        double gDirect = bcc.G(T, P, yConverged);
        double[] gradDirect = bcc.dG_dy(T, P, yConverged);
        double[][] hessDirect = bcc.d2G_dy2(T, P, yConverged);

        double maxAbsGradU = 0.0;
        for (int i = 0; i < NCF; i++) {
            maxAbsGradU = Math.max(maxAbsGradU, Math.abs(gradDirect[i]));
        }

        System.out.println();
        System.out.println("=".repeat(70));
        System.out.println("CROSS-CHECK " + label);
        System.out.println("=".repeat(70));
        System.out.printf(Locale.ROOT, "iterations        = %d%n", result.getIterations());
        System.out.printf(Locale.ROOT, "G initial         = %.10f%n", gInitial);
        System.out.printf(Locale.ROOT, "G final (expcvm10)= %.10f%n", gDirect);
        System.out.printf(Locale.ROOT, "G final (Hillert) = %.10f%n", gHillert);
        System.out.printf(Locale.ROOT, "|deltaG|          = %.6e%n", Math.abs(gDirect - gHillert));
        System.out.println("u initial (expcvm10) = " + java.util.Arrays.toString(
                java.util.Arrays.copyOfRange(y0, 0, NCF)));
        System.out.println("u final   (expcvm10) = " + java.util.Arrays.toString(
                java.util.Arrays.copyOfRange(yConverged, 0, NCF)));
        System.out.println("u final   (Hillert)  = " + java.util.Arrays.toString(uHillert));
        System.out.printf(Locale.ROOT, "max|dG/du| (expcvm10, converged) = %.6e%n", maxAbsGradU);

        // ------------------------------------------------------------
        // Assertion A: G agrees (same normalization confirmed in class
        // javadoc: per-formula-unit, same CEC convention, same SGTE
        // unaries).
        // ------------------------------------------------------------
        assertEquals(gHillert, gDirect, 1.0e-3,
                label + ": G must agree with the HillertSolver-compatible reference to 1e-3 J/mol.");

        // ------------------------------------------------------------
        // Assertion B: u agrees elementwise (identity ordering confirmed
        // by randomStateMatchesCEWorkbenchOrdering()).
        // ------------------------------------------------------------
        for (int i = 0; i < NCF; i++) {
            assertEquals(uHillert[i], yConverged[i], 5.0e-5,
                    label + ": u[" + i + "] must agree with the HillertSolver-compatible reference.");
        }

        // ------------------------------------------------------------
        // Assertion C: stationarity -- dG/du ~ 0 at the converged state,
        // for the leading ncf entries (the internal CVM correlation
        // functions), independent of the raw global solver residual
        // (which has its own conditioning-related floor -- see item 9).
        // ------------------------------------------------------------
        assertTrue(maxAbsGradU < 1.0e-2,
                label + ": max|dG/du| at the converged state should be small "
                + "(stationary point): " + maxAbsGradU);

        // ------------------------------------------------------------
        // Assertion D: mass balance / composition pinned correctly.
        // ------------------------------------------------------------
        assertEquals(target[0], stable.x[0], 1.0e-6);
        assertEquals(target[1], stable.x[1], 1.0e-6);

        // ------------------------------------------------------------
        // Item 11: curvature -- report whether H_uu is positive-definite
        // (locally minimum-like) via an unpivoted Cholesky pass. Not
        // asserted as a requirement (see class/task notes); reported.
        // ------------------------------------------------------------
        System.out.println("H_uu Cholesky pivots (expcvm10, converged state):");
        boolean allPositive = true;
        double[][] huu = new double[NCF][NCF];
        for (int i = 0; i < NCF; i++) {
            System.arraycopy(hessDirect[i], 0, huu[i], 0, NCF);
        }
        double[][] a = new double[NCF][NCF];
        for (int i = 0; i < NCF; i++) a[i] = huu[i].clone();
        for (int k = 0; k < NCF; k++) {
            double piv = a[k][k];
            System.out.printf(Locale.ROOT, "    pivot[%d] = %.6e%s%n", k, piv,
                    piv > 0 ? "" : "  <-- NOT POSITIVE");
            if (piv <= 0) {
                allPositive = false;
                break;
            }
            for (int i = k + 1; i < NCF; i++) {
                double f = a[i][k] / piv;
                for (int j = k; j < NCF; j++) a[i][j] -= f * a[k][j];
            }
        }
        System.out.println("H_uu positive-definite (locally minimum-like): " + allPositive);
    }

    // ------------------------------------------------------------------
    // Item 13: perturbed-start test at x=[0.6,0.4] -- proves
    // EquilibriumSolverV2 is a genuine attractor for this CVM state, not
    // merely accepting whatever initial u it was handed.
    // ------------------------------------------------------------------
    @Test
    void perturbedInitialStateConvergesToSameFinalStateAt60_40() throws Exception {
        TdbParser parser = new TdbParser();
        parser.load(TDB);
        CvmGibbsModel bcc = buildBccModel(parser);

        double[] target = {0.6, 0.4};
        double[] y0 = bcc.getInitialInternalVars(target);

        // Small valid perturbation of the leading (u) block only; leave
        // composition exactly as the target requires.
        double[] yPerturbed = y0.clone();
        double[] perturbation = {0.003, -0.004, 0.002, -0.0025};
        for (int i = 0; i < NCF; i++) {
            yPerturbed[i] += perturbation[i];
        }
        assertTrue(bcc.isValid(yPerturbed),
                "Perturbed initial state must remain valid before starting the solver.");

        // ---- run 1: normal (random-state) initialization ----
        EquilibriumResult normalResult = solveFixedComposition(bcc, target, y0);
        assertTrue(normalResult.isConverged());
        double[] yNormalFinal = normalResult.getStablePhases().get(0).y;

        // ---- run 2: perturbed initialization ----
        EquilibriumResult perturbedResult = solveFixedComposition(bcc, target, yPerturbed);
        assertTrue(perturbedResult.isConverged());
        double[] yPerturbedFinal = perturbedResult.getStablePhases().get(0).y;

        System.out.println();
        System.out.println("=== Perturbed-start test (x=[0.6,0.4]) ===");
        System.out.println("u0 normal    = " + java.util.Arrays.toString(
                java.util.Arrays.copyOfRange(y0, 0, NCF)));
        System.out.println("u0 perturbed = " + java.util.Arrays.toString(
                java.util.Arrays.copyOfRange(yPerturbed, 0, NCF)));
        System.out.println("u final (normal start)    = " + java.util.Arrays.toString(
                java.util.Arrays.copyOfRange(yNormalFinal, 0, NCF)));
        System.out.println("u final (perturbed start) = " + java.util.Arrays.toString(
                java.util.Arrays.copyOfRange(yPerturbedFinal, 0, NCF)));
        System.out.println("iterations (normal)    = " + normalResult.getIterations());
        System.out.println("iterations (perturbed) = " + perturbedResult.getIterations());

        for (int i = 0; i < NCF; i++) {
            assertEquals(yNormalFinal[i], yPerturbedFinal[i], 5.0e-5,
                    "u[" + i + "]: perturbed-start and normal-start solves must converge "
                    + "to the same CVM internal state.");
        }

        // Also cross-check the perturbed-start final state against the
        // independent Hillert reference at this composition.
        for (int i = 0; i < NCF; i++) {
            assertEquals(U_HILLERT_60_40[i], yPerturbedFinal[i], 5.0e-5,
                    "Perturbed-start u[" + i + "] must also agree with the Hillert reference.");
        }
    }

    private static EquilibriumResult solveFixedComposition(
            CvmGibbsModel bcc, double[] target, double[] y0) {
        List<GibbsEnergyModel> candidates = List.of(bcc);
        EquilibriumSolverV2 solver = new EquilibriumSolverV2();
        solver.setTolerance(1.0e-8);
        solver.setInitialStateForTest(
                new int[]{0},
                new double[][]{y0},
                new double[]{1.0});
        return solver.solve(T, P, target, candidates);
    }
}
