package test;

import session.CalculationSession;
import system.model.GibbsEnergyModel;
import system.model.cef.CefGibbs;

import java.util.Arrays;
import java.util.List;

/**
 * Verifies <b>every quantity on {@link GibbsEnergyModel}'s abstract
 * contract</b> -- the surface a Sundman phase-matrix/equilibrium-matrix
 * solver actually consumes (see {@code calc.equil.PhaseMatrixAssembler}) --
 * against exact symbolic reference values computed from <b>pycalphad
 * 0.11.1</b>.
 *
 * <p>Covers: {@code G}, {@code dG_dy}, {@code d2G_dy2}, {@code dG_dT},
 * {@code d2G_dydT}, {@code moles}, {@code dMoles_dy}. ({@code dG_dP} /
 * {@code d2G_dydP} are covered separately by
 * {@link CefVolumeContributionTest}, the only databases here with active
 * {@code V0} parameters; every phase used below is P-independent, so
 * {@code dG_dP == 0} is asserted here as a cheap corroborating check, not
 * the primary one.)
 *
 * <h2>Why this exists on top of the other CEF tests</h2>
 * {@link CefReferenceTermTest} checks {@code Gref} in isolation at pure
 * end-members; {@link CefMixingTermsTest} checks {@code Gid}/{@code Gex} in
 * isolation, report-only, at interior compositions; {@link
 * CefVolumeContributionTest} checks {@code Gvol}/{@code dG_dP}. None of
 * them touch {@code dG_dy}, {@code d2G_dy2}, {@code d2G_dydT},
 * {@code moles}, or {@code dMoles_dy} -- the exact quantities a Newton
 * solver assembles the phase matrix (Sundman 2015 Eq. 40) and equilibrium
 * matrix (Eq. 58) from. This test is the one place that exercises the full
 * contract surface at once, at the same (T, P, y) point per case, so a
 * single build gives a first-order Taylor-consistent bundle: reference
 * values here were generated by literal symbolic differentiation of
 * pycalphad's {@code Model.GM} (via sympy {@code .diff()}), not finite
 * differences, so {@code dG_dy}/{@code d2G_dy2}/{@code d2G_dydT} are exact
 * to the same precision as {@code G} itself, not merely
 * self-consistent with it.
 *
 * <h2>Fault isolation</h2>
 * Each of the 7 quantities is checked and reported <b>independently per
 * case</b>, never folded into one aggregate pass/fail -- so a wrong sign in
 * one Hessian entry, a wrong RK-order term in one gradient component, or a
 * scale error in {@code dMoles_dy} shows up as a failure naming exactly
 * (phase, T, quantity, index) rather than a single opaque "test failed".
 * {@code d2G_dy2} and {@code dMoles_dy} additionally get an independent
 * finite-difference cross-check against this project's own {@code dG_dy}/
 * {@code moles} (not pycalphad) -- if the FD check disagrees with the
 * analytic method but pycalphad also disagrees, the bug is almost
 * certainly in the analytic derivative formula, not a reference-value
 * transcription error, narrowing the search immediately.
 *
 * <h2>Tolerance</h2>
 * {@code G}, {@code dG_dy}, {@code d2G_dy2} carry the same known constant
 * ideal-mixing offset documented in {@link CefMixingTermsTest} (this
 * project's R = 8.3144598 CODATA-2014 vs. pycalphad's R = 8.31451 SGTE) --
 * report-only, printed but not gated. {@code dG_dT}/{@code d2G_dydT} carry
 * that same offset scaled by the ideal term's R-linearity, also
 * report-only. {@code moles}/{@code dMoles_dy} have no R-dependence at all
 * (pure linear site-fraction combinatorics) and are asserted at tight
 * tolerance -- a failure there is unambiguous and gates the build. The
 * finite-difference cross-checks are likewise gated at tight tolerance
 * since they compare this project against itself, not against pycalphad's
 * R convention.
 *
 * <p>Models are sourced through {@link CalculationSession}, matching the
 * established pattern in the other CEF tests.
 */
public class CefContractTest {

    private static final double P_REF = 101325.0;
    private static final double GATED_TOL = 1.0e-6;   // moles/dMoles_dy, FD cross-checks
    private static final double FD_H = 1.0e-6;         // finite-difference step for y
    private static final double FD_H_T = 1.0e-2;       // finite-difference step for T

    /** One fully-specified contract-value case, matching one row from the
     *  pycalphad-side generator (see gen_contract_ref.py in this session's
     *  scratchpad; values reproduced here as literals). */
    private static final class Case {
        final String tdb, phase;
        final String[] elements;
        final double T;
        final double[] y;
        final double G;
        final double[] dG_dy;
        final double[][] d2G_dy2;
        final double dG_dT;
        final double[] d2G_dydT;
        final double[] moles;
        final double[][] dMoles_dy;

        Case(String tdb, String phase, String[] elements, double T, double[] y,
             double G, double[] dG_dy, double[][] d2G_dy2,
             double dG_dT, double[] d2G_dydT,
             double[] moles, double[][] dMoles_dy) {
            this.tdb = tdb; this.phase = phase; this.elements = elements;
            this.T = T; this.y = y;
            this.G = G; this.dG_dy = dG_dy; this.d2G_dy2 = d2G_dy2;
            this.dG_dT = dG_dT; this.d2G_dydT = d2G_dydT;
            this.moles = moles; this.dMoles_dy = dMoles_dy;
        }
    }

    // ── pycalphad 0.11.1 reference values (exact symbolic differentiation
    //    of Model.GM * _site_ratio_normalization; site-fraction order is
    //    sublattice-major, alphabetical within sublattice) ──────────────

    private static final Case[] CASES = {

        new Case("data/VZR-re2.TDB", "BCC_A2", new String[]{"V", "ZR"},
            1200.0, new double[]{0.8, 0.2, 1.0},
            -6.0235559607e+04,
            new double[]{-4.4490740862e+04, -5.1977935123e+04, -2.5310644467e+04},
            new double[][]{
                {9.6125027560e+03, 2.8385973541e+04, -5.2241748393e+04},
                {2.8385973541e+04, 5.2830992944e+04, -4.5897329295e+04},
                {-5.2241748393e+04, -4.5897329295e+04, 2.9932200000e+04}
            },
            -7.4028296925e+01,
            new double[]{-5.8796130772e+01, -7.9461451633e+01, -4.4924200974e+01},
            new double[]{8.0000000000e-01, 2.0000000000e-01},
            new double[][]{
                {1.0, 0.0, 0.0},
                {0.0, 1.0, 0.0}
            }),

        new Case("data/VZR-re2.TDB", "BCC_A2", new String[]{"V", "ZR"},
            800.0, new double[]{0.3, 0.7, 1.0},
            -3.5131277173e+04,
            new double[]{-1.5872407765e+04, -2.7329800787e+04, -1.1113252181e+04},
            new double[][]{
                {2.6634891482e+04, 2.4072717613e+04, -1.4515662260e+04},
                {2.4072717613e+04, 4.4047444243e+03, -3.1608941729e+04},
                {-1.4515662260e+04, -3.1608941729e+04, 1.9954800000e+04}
            },
            -7.1789747332e+01,
            new double[]{-5.3135028436e+01, -6.7087253843e+01, -4.1767216093e+01},
            new double[]{3.0000000000e-01, 7.0000000000e-01},
            new double[][]{
                {1.0, 0.0, 0.0},
                {0.0, 1.0, 0.0}
            }),

        new Case("data/VZR-re2.TDB", "V2ZR", new String[]{"V", "ZR"},
            1200.0, new double[]{0.6, 0.4, 0.6, 0.4},
            -1.8274669095e+05,
            new double[]{-1.4726356697e+05, -1.5611195986e+05, -1.4703035414e+05, -1.6972521315e+05},
            new double[][]{
                {3.3258000000e+04, 2.1975250880e+04, -1.4841397540e+05, -1.5647814649e+05},
                {2.1975250880e+04, 4.9887000000e+04, -1.5715664331e+05, -1.5872093895e+05},
                {-1.4841397540e+05, -1.5715664331e+05, 1.6629000000e+04, 1.3463249952e+04},
                {-1.5647814649e+05, -1.5872093895e+05, 1.3463249952e+04, 2.4943500000e+04}
            },
            -2.3313790004e+02,
            new double[]{-1.9474750448e+02, -2.2777743559e+02, -2.1131842965e+02, -2.1367098052e+02},
            new double[]{1.8000000000e+00, 1.2000000000e+00},
            new double[][]{
                {2.0, 0.0, 1.0, 0.0},
                {0.0, 2.0, 0.0, 1.0}
            }),

        new Case("data/VZR-re2.TDB", "V2ZR", new String[]{"V", "ZR"},
            900.0, new double[]{0.3, 0.7, 0.8, 0.2},
            -1.1000469976e+05,
            new double[]{-9.9044824660e+04, -8.5229833621e+04, -8.6509779855e+04, -1.1615876774e+05},
            new double[][]{
                {4.9887000000e+04, 9.1415831800e+03, -9.5128425311e+04, -8.3783433571e+04},
                {9.1415831800e+03, 2.1380142857e+04, -9.1120725586e+04, -1.0980660137e+05},
                {-9.5128425311e+04, -9.1120725586e+04, 9.3538125000e+03, 5.8738505820e+03},
                {-8.3783433571e+04, -1.0980660137e+05, 5.8738505820e+03, 3.7415250000e+04}
            },
            -2.1221011598e+02,
            new double[]{-1.7988180790e+02, -1.9451964011e+02, -1.9128033005e+02, -2.0127904891e+02},
            new double[]{1.4000000000e+00, 1.6000000000e+00},
            new double[][]{
                {2.0, 0.0, 1.0, 0.0},
                {0.0, 2.0, 0.0, 1.0}
            }),

        new Case("data/VZR-re2.TDB", "LIQUID", new String[]{"V", "ZR"},
            1500.0, new double[]{0.45, 0.55},
            -8.9967938794e+04,
            new double[]{-6.8338599116e+04, -8.3818909449e+04},
            new double[][]{
                {2.6396188734e+04, 5.5580829518e+03},
                {5.5580829518e+03, 1.8376008775e+04}
            },
            -9.5050407305e+01,
            new double[]{-7.5993397324e+01, -9.0531831052e+01},
            new double[]{4.5000000000e-01, 5.5000000000e-01},
            new double[][]{
                {1.0, 0.0},
                {0.0, 1.0}
            }),

        new Case("data/steel1.TDB", "CEMENTITE", new String[]{"CR", "FE", "MO", "V", "C"},
            1000.0, new double[]{0.2, 0.5, 0.1, 0.2, 1.0},
            -2.0248673393e+05,
            new double[]{-1.9539497999e+05, -1.4022566995e+05, -1.4218235299e+05, -2.9946257828e+05, -1.6372601662e+05},
            new double[][]{
                {1.1962506000e+05, 7.7780000000e+03, 4.0000000000e+04, -3.7711200000e+04, -1.8019346542e+05},
                {7.7780000000e+03, 4.9887000000e+04, 0.0000000000e+00, -5.8287000000e+04, -1.4787965325e+05},
                {4.0000000000e+04, 0.0000000000e+00, 2.4943500000e+05, 0.0000000000e+00, -1.0969132172e+05},
                {-3.7711200000e+04, -5.8287000000e+04, 0.0000000000e+00, 1.2980994000e+05, -2.8426106371e+05},
                {-1.8019346542e+05, -1.4787965325e+05, -1.0969132172e+05, -2.8426106371e+05, 8.3145000000e+03}
            },
            -2.6283556024e+02,
            new double[]{-2.2785622899e+02, -2.4596394177e+02, -2.9492573099e+02, -2.1580619228e+02, -2.2407484293e+02},
            new double[]{6.0000000000e-01, 1.5000000000e+00, 3.0000000000e-01, 6.0000000000e-01, 1.0000000000e+00},
            new double[][]{
                {3.0, 0.0, 0.0, 0.0, 0.0},
                {0.0, 3.0, 0.0, 0.0, 0.0},
                {0.0, 0.0, 3.0, 0.0, 0.0},
                {0.0, 0.0, 0.0, 3.0, 0.0},
                {0.0, 0.0, 0.0, 0.0, 1.0}
            }),

        new Case("data/steel1.TDB", "CEMENTITE", new String[]{"CR", "FE", "MO", "V", "C"},
            1400.0, new double[]{0.5, 0.3, 0.1, 0.1, 1.0},
            -3.0764460237e+05,
            new double[]{-2.6016347687e+05, -2.5846103270e+05, -2.5595459640e+05, -4.1966798084e+05, -2.5520682775e+05},
            new double[][]{
                {6.6689892000e+04, 7.7800000000e+02, 4.0000000000e+04, -5.3554512000e+04, -2.7087905349e+05},
                {7.7800000000e+02, 1.1640300000e+05, 0.0000000000e+00, -6.3252600000e+04, -2.5133811880e+05},
                {4.0000000000e+04, 0.0000000000e+00, 3.4920900000e+05, 0.0000000000e+00, -2.1046715262e+05},
                {-5.3554512000e+04, -6.3252600000e+04, 0.0000000000e+00, 3.6496854000e+05, -3.7418053707e+05},
                {-2.7087905349e+05, -2.5133811880e+05, -2.1046715262e+05, -3.7418053707e+05, 1.1640300000e+04}
            },
            -2.9417592465e+02,
            new double[]{-2.4385209004e+02, -3.0329278656e+02, -3.3233486678e+02, -2.6789780979e+02, -2.5672037135e+02},
            new double[]{1.5000000000e+00, 9.0000000000e-01, 3.0000000000e-01, 3.0000000000e-01, 1.0000000000e+00},
            new double[][]{
                {3.0, 0.0, 0.0, 0.0, 0.0},
                {0.0, 3.0, 0.0, 0.0, 0.0},
                {0.0, 0.0, 3.0, 0.0, 0.0},
                {0.0, 0.0, 0.0, 3.0, 0.0},
                {0.0, 0.0, 0.0, 0.0, 1.0}
            }),
    };

    // ── bookkeeping: every failure is recorded with its exact coordinate
    //    (case, quantity, index) so the summary pinpoints the break ──────

    private static int totalChecks = 0;
    private static int gatedFailures = 0;
    private static final java.util.List<String> gatedFailureDetails = new java.util.ArrayList<>();

    // report-only (R-constant-offset) accumulators, kept per quantity so a
    // regression in just one of them is visible without wading through all
    private static double sumAbsG, maxAbsG;
    private static double sumAbsDgDy, maxAbsDgDy;
    private static double sumAbsD2gDy2, maxAbsD2gDy2;
    private static double sumAbsDgDT, maxAbsDgDT;
    private static double sumAbsD2gDydT, maxAbsD2gDydT;
    private static String worstG = "", worstDgDy = "", worstD2gDy2 = "", worstDgDT = "", worstD2gDydT = "";
    private static int reportOnlyCount = 0;

    public static void main(String[] args) throws Exception {
        System.out.println("============================================================");
        System.out.println("CefContractTest -- full GibbsEnergyModel abstract-contract");
        System.out.println("  surface vs. pycalphad 0.11.1 (exact symbolic derivatives)");
        System.out.println("============================================================");

        for (Case c : CASES) {
            System.out.println();
            System.out.println("--- " + c.phase + " (" + c.tdb + ")  T=" + c.T
                    + "  y=" + Arrays.toString(c.y) + " ---");

            CefGibbs g = buildCefGibbs(c.tdb, Arrays.asList(c.elements), c.phase);
            reportOnlyCount++;

            checkG(c, g);
            checkDgDy(c, g);
            checkD2gDy2(c, g);
            checkDgDT(c, g);
            checkD2gDydT(c, g);
            checkMoles(c, g);
            checkDMolesDy(c, g);
            checkDgDpZero(c, g);
        }

        System.out.println();
        System.out.println("============================================================");
        System.out.println("Report-only summary (R-constant convention offset expected;"
                + " watch, do not gate):");
        System.out.printf("  G         mean|diff|=%.4f  max|diff|=%.4f (at %s)%n",
                sumAbsG / reportOnlyCount, maxAbsG, worstG);
        System.out.printf("  dG_dy     mean|diff|=%.4f  max|diff|=%.4f (at %s)%n",
                sumAbsDgDy / reportOnlyCount, maxAbsDgDy, worstDgDy);
        System.out.printf("  d2G_dy2   mean|diff|=%.4f  max|diff|=%.4f (at %s)%n",
                sumAbsD2gDy2 / reportOnlyCount, maxAbsD2gDy2, worstD2gDy2);
        System.out.printf("  dG_dT     mean|diff|=%.4f  max|diff|=%.4f (at %s)%n",
                sumAbsDgDT / reportOnlyCount, maxAbsDgDT, worstDgDT);
        System.out.printf("  d2G_dydT  mean|diff|=%.4f  max|diff|=%.4f (at %s)%n",
                sumAbsD2gDydT / reportOnlyCount, maxAbsD2gDydT, worstD2gDydT);
        System.out.println();
        System.out.println("Gated summary (moles/dMoles_dy vs pycalphad, and this project's");
        System.out.println("own finite-difference cross-checks -- no R-constant ambiguity):");
        System.out.printf("  %d / %d gated checks passed%n", totalChecks - gatedFailures, totalChecks);
        if (gatedFailures > 0) {
            System.out.println("  FAILING CHECKS:");
            for (String d : gatedFailureDetails) System.out.println("    " + d);
        }

        System.out.println();
        if (gatedFailures == 0) {
            System.out.println("ALL GATED CEF CONTRACT CHECKS PASSED");
        } else {
            System.out.println(gatedFailures + " GATED CEF CONTRACT CHECK(S) FAILED");
            System.exit(1);
        }
    }

    // ── per-quantity checks ──────────────────────────────────────────

    private static void checkG(Case c, CefGibbs g) {
        double actual = g.G(c.T, P_REF, c.y);
        double diff = actual - c.G;
        sumAbsG += Math.abs(diff);
        if (Math.abs(diff) > maxAbsG) { maxAbsG = Math.abs(diff); worstG = where(c); }
        System.out.printf("  G         project=%.4f  pycalphad=%.4f  diff=%.4f%n", actual, c.G, diff);
    }

    private static void checkDgDy(Case c, CefGibbs g) {
        double[] actual = g.dG_dy(c.T, P_REF, c.y);
        double maxDiff = 0;
        for (int i = 0; i < actual.length; i++) {
            double diff = actual[i] - c.dG_dy[i];
            maxDiff = Math.max(maxDiff, Math.abs(diff));
        }
        sumAbsDgDy += maxDiff;
        if (maxDiff > maxAbsDgDy) { maxAbsDgDy = maxDiff; worstDgDy = where(c); }
        System.out.printf("  dG_dy     project=%s%n", Arrays.toString(actual));
        System.out.printf("            pycalphad=%s  maxdiff=%.4f%n", Arrays.toString(c.dG_dy), maxDiff);
    }

    private static void checkD2gDy2(Case c, CefGibbs g) {
        double[][] actual = g.d2G_dy2(c.T, P_REF, c.y);
        double maxDiff = 0;
        int nip = c.y.length;
        for (int i = 0; i < nip; i++) {
            for (int j = 0; j < nip; j++) {
                maxDiff = Math.max(maxDiff, Math.abs(actual[i][j] - c.d2G_dy2[i][j]));
            }
        }
        sumAbsD2gDy2 += maxDiff;
        if (maxDiff > maxAbsD2gDy2) { maxAbsD2gDy2 = maxDiff; worstD2gDy2 = where(c); }
        System.out.printf("  d2G_dy2   maxdiff-vs-pycalphad=%.4f%n", maxDiff);

        // Independent finite-difference cross-check of d2G_dy2 against
        // this project's OWN dG_dy (not pycalphad) -- isolates whether a
        // disagreement (if any, beyond the R-offset already reported
        // above) is in the Hessian formula itself vs. a reference-value
        // transcription issue.
        //
        // y is constrained (each sublattice's constituents sum to 1), so a
        // naive single-index bump y[i] += h leaves the manifold and
        // CefGibbs correctly rejects it (checkY). Instead perturb a PAIR
        // (i, k) in the same sublattice, y[i] += h, y[k] -= h, which stays
        // on the manifold; central-differencing dG_dy along that direction
        // gives the directional second derivative
        //   (H*(e_i - e_k))_j  =  H[i][j] - H[k][j]
        // for every row j -- not each H[i][j] in isolation, but still a
        // real, gated cross-check of the Hessian formula against dG_dy.
        int[] offs = g.offsets();
        int[] ncSL = g.constituentsPerSublattice();
        for (int s = 0; s < g.numSublattices(); s++) {
            if (ncSL[s] < 2) continue; // no pair available on this sublattice
            int i = offs[s];
            int k = offs[s] + 1;
            double[] yPlus = c.y.clone();
            double[] yMinus = c.y.clone();
            yPlus[i] += FD_H; yPlus[k] -= FD_H;
            yMinus[i] -= FD_H; yMinus[k] += FD_H;
            double[] gradPlus = g.dG_dy(c.T, P_REF, yPlus);
            double[] gradMinus = g.dG_dy(c.T, P_REF, yMinus);
            for (int j = 0; j < nip; j++) {
                double fdDirectional = (gradPlus[j] - gradMinus[j]) / (2 * FD_H);
                double analyticDirectional = actual[i][j] - actual[k][j];
                gate("d2G_dy2 directional (i=" + i + ",k=" + k + ")[" + j + "] vs FD(dG_dy)",
                        where(c), fdDirectional, analyticDirectional, 1.0e-1);
            }
        }
    }

    private static void checkDgDT(Case c, CefGibbs g) {
        double actual = g.dG_dT(c.T, P_REF, c.y);
        double diff = actual - c.dG_dT;
        sumAbsDgDT += Math.abs(diff);
        if (Math.abs(diff) > maxAbsDgDT) { maxAbsDgDT = Math.abs(diff); worstDgDT = where(c); }
        System.out.printf("  dG_dT     project=%.6f  pycalphad=%.6f  diff=%.6f%n", actual, c.dG_dT, diff);

        // Independent finite-difference cross-check against this
        // project's own G(T,P,y), central difference in T.
        double gPlus = g.G(c.T + FD_H_T, P_REF, c.y);
        double gMinus = g.G(c.T - FD_H_T, P_REF, c.y);
        double fd = (gPlus - gMinus) / (2 * FD_H_T);
        gate("dG_dT vs FD(G)", where(c), fd, actual, 1.0e-1);
    }

    private static void checkD2gDydT(Case c, CefGibbs g) {
        double[] actual = g.d2G_dydT(c.T, P_REF, c.y);
        double maxDiff = 0;
        for (int i = 0; i < actual.length; i++) {
            maxDiff = Math.max(maxDiff, Math.abs(actual[i] - c.d2G_dydT[i]));
        }
        sumAbsD2gDydT += maxDiff;
        if (maxDiff > maxAbsD2gDydT) { maxAbsD2gDydT = maxDiff; worstD2gDydT = where(c); }
        System.out.printf("  d2G_dydT  maxdiff-vs-pycalphad=%.4f%n", maxDiff);

        // Independent finite-difference cross-check against this
        // project's own dG_dy(T,P,y), central difference in T.
        double[] gradPlus = g.dG_dy(c.T + FD_H_T, P_REF, c.y);
        double[] gradMinus = g.dG_dy(c.T - FD_H_T, P_REF, c.y);
        for (int i = 0; i < actual.length; i++) {
            double fd = (gradPlus[i] - gradMinus[i]) / (2 * FD_H_T);
            gate("d2G_dydT[" + i + "] vs FD(dG_dy)", where(c), fd, actual[i], 1.0e-1);
        }
    }

    private static void checkMoles(Case c, CefGibbs g) {
        double[] actual = g.moles(c.y);
        for (int i = 0; i < c.elements.length; i++) {
            gate("moles[" + c.elements[i] + "]", where(c), actual[i], c.moles[i], GATED_TOL);
        }
    }

    private static void checkDMolesDy(Case c, CefGibbs g) {
        double[][] actual = g.dMoles_dy();
        for (int A = 0; A < c.elements.length; A++) {
            for (int m = 0; m < c.y.length; m++) {
                gate("dMoles_dy[" + c.elements[A] + "][" + m + "]", where(c),
                        actual[A][m], c.dMoles_dy[A][m], GATED_TOL);
            }
        }
    }

    private static void checkDgDpZero(Case c, CefGibbs g) {
        // None of these phases have V0 parameters, so dG_dP must be
        // exactly 0 -- a cheap corroborating check that the pressure
        // contribution correctly no-ops for phases without volume data
        // (see CefVolumeContributionTest for the phases that DO have V0).
        double dGdP = g.dG_dP(c.T, P_REF, c.y);
        gate("dG_dP (no V0 params, expect 0)", where(c), dGdP, 0.0, 1.0e-9);
    }

    // ── shared plumbing ──────────────────────────────────────────────

    private static String where(Case c) {
        return c.phase + " T=" + (int) c.T;
    }

    private static void gate(String label, String where, double actual, double expected, double tol) {
        totalChecks++;
        double diff = Math.abs(actual - expected);
        if (diff > tol) {
            gatedFailures++;
            gatedFailureDetails.add(where + "  " + label
                    + "  actual=" + actual + "  expected=" + expected + "  diff=" + diff);
        }
    }

    private static CefGibbs buildCefGibbs(String tdb, List<String> elements,
                                          String phaseName) throws Exception {
        CalculationSession session = new CalculationSession();
        session.setModel(tdb, elements, Arrays.asList(phaseName));
        List<GibbsEnergyModel> models = session.currentSystem().phaseModels();
        if (models.size() != 1) {
            throw new IllegalStateException("Expected exactly one " + phaseName
                    + " model, but obtained " + models.size());
        }
        GibbsEnergyModel model = models.get(0);
        if (!(model instanceof CefGibbs)) {
            throw new IllegalStateException(phaseName
                    + " was not constructed as a CEF model (got "
                    + model.getClass().getSimpleName() + ").");
        }
        return (CefGibbs) model;
    }
}
